"use client";

import { useCallback, useEffect, useState } from "react";
import { API, Job } from "@/lib/api";

type ReviewData = { hero: string; role: string; result: string; kills: string; deaths: string; assists: string };

function ReviewCard({ job, onDone }: { job: Job; onDone: () => void }) {
  const parsed = job.parsed_payload || {};
  const sourceRows = Array.isArray(parsed.matches) ? parsed.matches as Record<string, unknown>[] : [parsed];
  const [rows, setRows] = useState<ReviewData[]>(sourceRows.map(row => ({ hero: String(row.hero || ""), role: String(row.role || "unknown"), result: String(row.result || "win"), kills: String(row.kills ?? 0), deaths: String(row.deaths ?? 0), assists: String(row.assists ?? 0) })));
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const update = (index: number, key: keyof ReviewData, value: string) => setRows(current => current.map((row, rowIndex) => rowIndex === index ? { ...row, [key]: value } : row));
  async function save() { setSaving(true); setError(""); const matches = rows.filter(row => row.hero.trim()).map(row => ({ ...row, kills: Number(row.kills), deaths: Number(row.deaths), assists: Number(row.assists) })); const response = await fetch(`${API}/api/v1/jobs/${job.id}/manual-review-batch`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ matches }) }); if (!response.ok) { const body = await response.json().catch(() => ({})); setError(body.detail || "Không thể lưu trận."); setSaving(false); return; } onDone(); }
  return <div className="card"><div className="flex justify-between"><b>{job.status === "review" ? "AI cần bạn duyệt" : "Chờ AI / nhập thủ công"}</b><span className="text-slate-400">{job.id.slice(0, 8)}</span></div><p className="mt-2 text-sm text-slate-400">{rows.length} dòng trận. Sửa các ô cần thiết rồi lưu toàn bộ.</p><div className="mt-4 space-y-3">{rows.map((row, index) => <div className="grid gap-2 rounded-lg border border-slate-800 p-3 md:grid-cols-6" key={index}><input className="input" value={row.hero} onChange={event => update(index, "hero", event.target.value)} placeholder="Tên tướng"/><select className="input" value={row.role} onChange={event => update(index, "role", event.target.value)}>{["unknown", "dragon", "jungle", "mid", "slayer", "support"].map(role => <option key={role}>{role}</option>)}</select><select className="input" value={row.result} onChange={event => update(index, "result", event.target.value)}><option value="win">Thắng</option><option value="loss">Thua</option></select><input className="input" type="number" min="0" value={row.kills} onChange={event => update(index, "kills", event.target.value)} placeholder="K"/><input className="input" type="number" min="0" value={row.deaths} onChange={event => update(index, "deaths", event.target.value)} placeholder="D"/><input className="input" type="number" min="0" value={row.assists} onChange={event => update(index, "assists", event.target.value)} placeholder="A"/></div>)}</div><button className="button mt-4" disabled={saving || !rows.some(row => row.hero.trim())} onClick={save}>{saving ? "Đang lưu…" : `Lưu ${rows.filter(row => row.hero.trim()).length} trận đã duyệt`}</button>{error && <p className="mt-3 text-sm text-rose-400">{error}</p>}</div>;
}

export function ImportReview({ playerId }: { playerId: string }) {
  const [files, setFiles] = useState<FileList | null>(null); const [jobs, setJobs] = useState<Job[]>([]); const [loading, setLoading] = useState(false); const [uploadError, setUploadError] = useState("");
  const load = useCallback(() => fetch(`${API}/api/v1/players/${playerId}/jobs`).then(response => response.ok ? response.json() : []).then(setJobs), [playerId]);
  useEffect(() => { void load(); const timer = setInterval(load, 2500); return () => clearInterval(timer); }, [load]);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!files) return; setLoading(true); setUploadError(""); const form = new FormData(); Array.from(files).forEach(file => form.append("files", file)); const response = await fetch(`${API}/api/v1/players/${playerId}/screenshots`, { method: "POST", body: form }); if (!response.ok) { const body = await response.json().catch(() => ({})); setUploadError(body.detail || "Tải ảnh thất bại."); } setLoading(false); void load(); }
  return <div className="space-y-5"><form onSubmit={submit} className="card"><h2 className="mb-2 font-semibold">Nhập ảnh lịch sử đấu</h2><p className="mb-3 text-sm text-slate-400">Hỗ trợ ảnh nhiều dòng trận như Lịch sử đấu. AI sẽ tách từng dòng, bạn duyệt lại trước khi lưu.</p><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={event => setFiles(event.target.files)}/><button className="button ml-3" disabled={!files || loading}>{loading ? "Đang tải…" : "Tải ảnh lên"}</button>{uploadError && <p className="mt-3 text-sm text-rose-400">{uploadError}</p>}</form><section className="space-y-3">{jobs.length === 0 && <div className="card text-slate-400">Chưa có ảnh nào. Tải ảnh lịch sử đấu để bắt đầu.</div>}{jobs.map(job => job.status === "completed" ? <div className="card" key={job.id}><b>Đã lưu</b><span className="ml-3 text-slate-400">{job.id.slice(0, 8)}</span></div> : <ReviewCard key={job.id} job={job} onDone={load}/>)}</section></div>;
}
