"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { API, getMatches, MatchRecord } from "@/lib/api";

export function MatchHistory({ playerId }: { playerId: string }) {
  const [matches, setMatches] = useState<MatchRecord[]>([]); const [error, setError] = useState("");
  const load = useCallback(() => getMatches(playerId).then(setMatches).catch(() => setError("Không thể tải lịch sử trận.")), [playerId]);
  useEffect(() => { void load(); }, [load]);
  async function remove(id: string) { if (!window.confirm("Xoá trận này khỏi hồ sơ?")) return; const response = await fetch(`${API}/api/v1/matches/${id}`, { method: "DELETE" }); if (!response.ok) { setError("Không thể xoá trận."); return; } void load(); }
  async function edit(match: MatchRecord) { const hero = window.prompt("Tên tướng", match.hero); if (!hero) return; const role = window.prompt("Role: dragon, jungle, mid, slayer, support", match.role); if (!role) return; const result = window.prompt("Kết quả: win hoặc loss", match.result); if (!result) return; const kda = window.prompt("K/D/A", `${match.kills}/${match.deaths}/${match.assists}`); if (!kda) return; const values = kda.split("/").map(Number); if (values.length !== 3 || values.some(value => !Number.isInteger(value) || value < 0)) { setError("KDA phải có dạng 4/1/14."); return; } const response = await fetch(`${API}/api/v1/matches/${match.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ hero, role, result, kills: values[0], deaths: values[1], assists: values[2] }) }); if (!response.ok) { setError("Không thể cập nhật trận. Kiểm tra tên tướng và dữ liệu nhập."); return; } void load(); }
  return <section className="card"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Lịch sử trận</h2><span className="text-sm text-slate-400">{matches.length} trận</span></div>{error && <p className="mt-3 text-sm text-rose-400">{error}</p>}{matches.length === 0 ? <p className="mt-4 text-slate-400">Chưa có trận nào được duyệt.</p> : <div className="mt-4 space-y-2">{matches.map(match => <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-800 p-3" key={match.id}><Link href={`/heroes/${match.hero_id}`} className="flex items-center gap-3 hover:text-cyan-300"><span className="h-10 w-10 rounded bg-slate-800 bg-cover bg-center" role="img" aria-label={match.hero} style={match.image_url ? { backgroundImage: `url(${match.image_url})` } : undefined}/><span className="font-semibold">{match.hero}</span></Link><span className={match.result === "win" ? "text-emerald-400" : "text-rose-400"}>{match.result === "win" ? "Thắng" : "Thua"}</span><span>{match.kills}/{match.deaths}/{match.assists}</span><span className="capitalize text-slate-400">{match.role}</span><div className="flex gap-3"><button className="text-sm text-cyan-300 hover:text-cyan-200" onClick={() => edit(match)}>Sửa</button><button className="text-sm text-rose-300 hover:text-rose-200" onClick={() => remove(match.id)}>Xoá</button></div></div>)}</div>}</section>;
}
