"""initial schema"""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("players", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("name", sa.String(80), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.UniqueConstraint("name")); op.create_index("ix_players_name", "players", ["name"])
    op.create_table("heroes", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("name", sa.String(80), nullable=False), sa.Column("role", sa.String(30), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.UniqueConstraint("name")); op.create_index("ix_heroes_name", "heroes", ["name"])
    op.create_table("imported_images", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("player_id", sa.Uuid(), sa.ForeignKey("players.id", ondelete="CASCADE"), nullable=False), sa.Column("original_name", sa.String(255), nullable=False), sa.Column("stored_path", sa.String(500), nullable=False, unique=True), sa.Column("sha256", sa.String(64), nullable=False, unique=True), sa.Column("media_type", sa.String(50), nullable=False), sa.Column("size_bytes", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"))); op.create_index("ix_imported_images_player_id", "imported_images", ["player_id"]); op.create_index("ix_imported_images_sha256", "imported_images", ["sha256"])
    op.create_table("parsing_jobs", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("image_id", sa.Uuid(), sa.ForeignKey("imported_images.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("status", sa.String(20), nullable=False), sa.Column("parsed_payload", sa.JSON(), nullable=True), sa.Column("error", sa.Text(), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"))); op.create_index("ix_parsing_jobs_status", "parsing_jobs", ["status"]); op.create_index("ix_jobs_status_created", "parsing_jobs", ["status", "created_at"])
    op.create_table("matches", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("player_id", sa.Uuid(), sa.ForeignKey("players.id", ondelete="CASCADE"), nullable=False), sa.Column("hero_id", sa.Uuid(), sa.ForeignKey("heroes.id"), nullable=False), sa.Column("played_at", sa.DateTime(timezone=True), nullable=False), sa.Column("role", sa.String(30), nullable=False), sa.Column("result", sa.String(10), nullable=False), sa.Column("kills", sa.Integer(), nullable=False), sa.Column("deaths", sa.Integer(), nullable=False), sa.Column("assists", sa.Integer(), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("source_hash", sa.String(64), nullable=True, unique=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"))); op.create_index("ix_matches_player_id", "matches", ["player_id"]); op.create_index("ix_matches_hero_id", "matches", ["hero_id"]); op.create_index("ix_matches_played_at", "matches", ["played_at"])
    op.create_table("match_players", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("match_id", sa.Uuid(), sa.ForeignKey("matches.id", ondelete="CASCADE"), nullable=False), sa.Column("player_id", sa.Uuid(), sa.ForeignKey("players.id", ondelete="CASCADE"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.UniqueConstraint("match_id", "player_id", name="uq_match_players")); op.create_index("ix_match_players_match_id", "match_players", ["match_id"]); op.create_index("ix_match_players_player_id", "match_players", ["player_id"])

def downgrade():
    op.drop_table("match_players"); op.drop_table("matches"); op.drop_table("parsing_jobs"); op.drop_table("imported_images"); op.drop_table("heroes"); op.drop_table("players")
